<a href="https://colab.research.google.com/github/kvs1998/PythonForDSandML/blob/main/pytorch_ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.10.0+cu111'

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
arr.dtype

dtype('int64')

In [6]:
type(arr)

numpy.ndarray

In [9]:
x = torch.from_numpy(arr) #works only on numpy array

In [10]:
x.dtype

torch.int64

In [11]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [13]:
arr2d = np.arange(0.0, 12.0)

In [14]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [17]:
x2 = arr2d.reshape(4,3)
x2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [18]:
my_arr = np.arange(0,10)

In [19]:
my_tensor = torch.tensor(my_arr) #creates copy of original tensor

In [21]:
my_tensor2 = torch.from_numpy(my_arr) 

In [24]:
my_arr[0]=99

In [25]:
my_tensor, my_tensor2

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9]))