<a href="https://colab.research.google.com/github/kvs1998/PythonForDSandML/blob/main/pytorch_ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensor basics 1

In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'1.10.0+cu111'

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr.dtype

dtype('int64')

In [6]:
type(arr)

numpy.ndarray

In [7]:
x = torch.from_numpy(arr) #works only on numpy array

In [8]:
x.dtype

torch.int64

In [9]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [10]:
arr2d = np.arange(0.0, 12.0)

In [11]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [12]:
x2 = arr2d.reshape(4,3)
x2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [13]:
my_arr = np.arange(0,10)

In [14]:
my_tensor = torch.tensor(my_arr) #creates copy of original tensor

In [15]:
my_tensor2 = torch.from_numpy(my_arr) 

In [16]:
my_arr[0]=99

In [17]:
my_tensor, my_tensor2

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9]))

### Tensor basic 2

In [18]:
torch.FloatTensor([1,2,4])

tensor([1., 2., 4.])

In [19]:
torch.empty(2,3) #placeholder

tensor([[6.3385e+25, 3.0617e-41, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00]])

In [20]:
torch.zeros(2,4, dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [21]:
torch.ones(3) #(1,3)

tensor([1., 1., 1.])

In [22]:
torch.arange(0,20,2).reshape(2,5)

tensor([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]])

In [23]:
torch.linspace(0,5,3)

tensor([0.0000, 2.5000, 5.0000])

In [24]:
 a = torch.tensor([1,2,3])

In [25]:
a = a.type(torch.int32)

In [26]:
a.shape

torch.Size([3])

In [35]:
x = torch.zeros(2,5)

In [36]:
torch.rand_like(x) #between 0 and 1 (uniform distribution)

tensor([[0.2379, 0.4011, 0.5317, 0.2884, 0.1266],
        [0.5808, 0.9911, 0.9332, 0.7632, 0.6566]])

In [37]:
torch.randn_like(x) #standard normal distribution

tensor([[ 0.8887, -1.9612,  0.2208,  0.2689,  1.8441],
        [-0.6368, -0.0666,  0.6781, -1.4909, -1.3471]])

In [38]:
torch.randint_like(x, 0, 11)

tensor([[ 5.,  8., 10.,  7.,  9.],
        [ 7.,  9.,  2.,  6.,  3.]])

In [45]:
torch.manual_seed(3) #has to be in same cell for same results
torch.rand(2,3)

tensor([[0.0043, 0.1056, 0.2858],
        [0.0270, 0.4716, 0.0601]])

### Tensor Operations

In [47]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [49]:
x[1][1], x[1,1] #still returns tensor

(tensor(3), tensor(3))

In [50]:
x[:,1] #all rows but only first column

tensor([1, 3, 5])

In [51]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [52]:
x=torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
x.view(2,5) #doesnt reshape

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [54]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x = torch.arange(10)
x.shape

torch.Size([10])

In [56]:
z = x.view(2,5)
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [57]:
x[0]=999

In [58]:
x, z #even z has changed

(tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9]),
 tensor([[999,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9]]))

In [59]:
x.view(2, -1) #-1 means infer whats the 2nd dimension

tensor([[999,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [60]:
a = torch.arange(4)
b = torch.arange(4)
a+b

tensor([0, 2, 4, 6])

In [61]:
torch.add(a,b)

tensor([0, 2, 4, 6])

In [62]:
a.add_(b) #a = a+b

tensor([0, 2, 4, 6])

In [64]:
a.add(b),a ,b

(tensor([0, 3, 6, 9]), tensor([0, 2, 4, 6]), tensor([0, 1, 2, 3]))